EDB0_predname=esrc_KEY_NUMBER
EDB0_type=INMEMORY
EDB0_param0=data
EDB0_param1=esrc_KEY_NUMBER
EDB1_predname=esrc_KEY_SENSITIVE
EDB1_type=INMEMORY
EDB1_param0=data
EDB1_param1=esrc_KEY_SENSITIVE
EDB2_predname=esrc_RAND
EDB2_type=INMEMORY
EDB2_param0=data
EDB2_param1=esrc_RAND
EDB3_predname=esrc_RAND_NUMBER
EDB3_type=INMEMORY
EDB3_param0=data
EDB3_param1=esrc_RAND_NUMBER
EDB4_predname=esrc_REC_ALL_INC
EDB4_type=INMEMORY
EDB4_param0=data
EDB4_param1=esrc_REC_ALL_INC
EDB5_predname=esrc_REC_RAND_VAR
EDB5_type=INMEMORY
EDB5_param0=data
EDB5_param1=esrc_REC_RAND_VAR
EDB6_predname=esrc_Time
EDB6_type=INMEMORY
EDB6_param0=data
EDB6_param1=esrc_Time
EDB7_predname=esrc_assign
EDB7_type=INMEMORY
EDB7_param0=data
EDB7_param1=esrc_assign
EDB8_predname=esrc_binary_constant
EDB8_type=INMEMORY
EDB8_param0=data
EDB8_param1=esrc_binary_constant
EDB9_predname=esrc_icmp_assign
EDB9_type=INMEMORY
EDB9_param0=data
EDB9_param1=esrc_icmp_assign
EDB10_predname=esrc_load_assign
EDB10_type=INMEMORY
EDB10_param0=data
EDB10_param1=esrc_load_assign
EDB11_predname=esrc_share
EDB11_type=INMEMORY
EDB11_param0=data
EDB11_param1=esrc_share
EDB12_predname=esrc_store_assign
EDB12_type=INMEMORY
EDB12_param0=data
EDB12_param1=esrc_store_assign
EDB13_predname=esrc_trunc_assign
EDB13_type=INMEMORY
EDB13_param0=data
EDB13_param1=esrc_trunc_assign
EDB14_predname=esrc_xor_assign_left
EDB14_type=INMEMORY
EDB14_param0=data
EDB14_param1=esrc_xor_assign_left
EDB15_predname=esrc_xor_assign_right
EDB15_type=INMEMORY
EDB15_param0=data
EDB15_param1=esrc_xor_assign_right
EDB16_predname=esrc_zext_assign
EDB16_type=INMEMORY
EDB16_param0=data
EDB16_param1=esrc_zext_assign
EDB17_predname=equiv
EDB17_type=INMEMORY
EDB17_param0=data
EDB17_param1=equiv
