EDB0_predname=esrc_address_array
EDB0_type=INMEMORY
EDB0_param0=data
EDB0_param1=esrc_address_array
EDB1_predname=esrc_address_in_data_refined
EDB1_type=INMEMORY
EDB1_param0=data
EDB1_param1=esrc_address_in_data_refined
EDB2_predname=esrc_data_limit
EDB2_type=INMEMORY
EDB2_param0=data
EDB2_param1=esrc_data_limit
EDB3_predname=esrc_pointer_size
EDB3_type=INMEMORY
EDB3_param0=data
EDB3_param1=esrc_pointer_size
EDB4_predname=esrc_preferred_data_access
EDB4_type=INMEMORY
EDB4_param0=data
EDB4_param1=esrc_preferred_data_access
EDB5_predname=esrc_string_candidate_refined
EDB5_type=INMEMORY
EDB5_param0=data
EDB5_param1=esrc_string_candidate_refined
EDB6_predname=esrc_subsequent_string_candidate
EDB6_type=INMEMORY
EDB6_param0=data
EDB6_param1=esrc_subsequent_string_candidate
EDB7_predname=esrc_ctx__aligned_
EDB7_type=INMEMORY
EDB7_param0=data
EDB7_param1=esrc_ctx__aligned_
EDB8_predname=esrc_ctx__data_access_
EDB8_type=INMEMORY
EDB8_param0=data
EDB8_param1=esrc_ctx__data_access_
EDB9_predname=esrc_ctx__data_object_bias_
EDB9_type=INMEMORY
EDB9_param0=data
EDB9_param1=esrc_ctx__data_object_bias_
EDB10_predname=esrc_ctx__long_string_
EDB10_type=INMEMORY
EDB10_param0=data
EDB10_param1=esrc_ctx__long_string_
EDB11_predname=esrc_ctx__other_
EDB11_type=INMEMORY
EDB11_param0=data
EDB11_param1=esrc_ctx__other_
EDB12_predname=esrc_ctx__overlaps_string_
EDB12_type=INMEMORY
EDB12_param0=data
EDB12_param1=esrc_ctx__overlaps_string_
EDB13_predname=esrc_ctx__pointer_array_
EDB13_type=INMEMORY
EDB13_param0=data
EDB13_param1=esrc_ctx__pointer_array_
EDB14_predname=esrc_ctx__string_basic_point_
EDB14_type=INMEMORY
EDB14_param0=data
EDB14_param1=esrc_ctx__string_basic_point_
EDB15_predname=esrc_ctx__string_has_string_neighbors_
EDB15_type=INMEMORY
EDB15_param0=data
EDB15_param1=esrc_ctx__string_has_string_neighbors_
EDB16_predname=esrc_ctx__string_that_has_reference_
EDB16_type=INMEMORY
EDB16_param0=data
EDB16_param1=esrc_ctx__string_that_has_reference_
EDB17_predname=esrc_ctx__string_
EDB17_type=INMEMORY
EDB17_param0=data
EDB17_param1=esrc_ctx__string_
EDB18_predname=esrc_ctx__symbol_
EDB18_type=INMEMORY
EDB18_param0=data
EDB18_param1=esrc_ctx__symbol_
EDB19_predname=esrc_ctx__1
EDB19_type=INMEMORY
EDB19_param0=data
EDB19_param1=esrc_ctx__1
EDB20_predname=esrc_ctx__2
EDB20_type=INMEMORY
EDB20_param0=data
EDB20_param1=esrc_ctx__2
EDB21_predname=esrc_ctx_n1
EDB21_type=INMEMORY
EDB21_param0=data
EDB21_param1=esrc_ctx_n1
EDB22_predname=esrc_ctx_n2
EDB22_type=INMEMORY
EDB22_param0=data
EDB22_param1=esrc_ctx_n2
EDB23_predname=esrc_ctx_n3
EDB23_type=INMEMORY
EDB23_param0=data
EDB23_param1=esrc_ctx_n3
EDB24_predname=esrc_ctx_n4
EDB24_type=INMEMORY
EDB24_param0=data
EDB24_param1=esrc_ctx_n4
EDB25_predname=esrc_ctx_n5
EDB25_type=INMEMORY
EDB25_param0=data
EDB25_param1=esrc_ctx_n5
EDB26_predname=equiv
EDB26_type=INMEMORY
EDB26_param0=data
EDB26_param1=equiv
